### PR TITLE
fix five mile shp to match geojson source + add 3-mile buffer to small airports (geojson and shape)

### PR DESCRIPTION
**Pull request by smathermather**
reference issue #39

### CODE REVIEW

**Comment by pnorman** [comment]
FAA or similar reference for the 3 mile value for small airports?

**Comment by tschundler** [comment]
I think the 3 mile rule is based on AMA Safety Code rather than FAA

**Comment by tmcw** [comment]
Thanks for the PR! We've deprecated this project, so I'm closing this PR.

**Comment by smathermather** [comment]
Cheers.

**Pull request closed without merging**
